# Checking out new VCF inds
# Basically a temporary file

# read in vcf metadata
vcf_info <- read.csv("~/Documents/PhD/Research/capsella_sample_info/generated_mkwb/Capsella_vcf_metadata.txt",
                     header = T, sep = "\t")
# read in list of samples in VCF generated by bcftools query -l <VCF>
invcf <- read.csv("~//Documents/PhD/Research/vcf_filtering/july14_vcf_inds.txt",
                  header = F, sep = "\t")
# load dplyr
library(dplyr)

# big data frame
dat <- left_join(invcf, vcf_info, join_by("V1" == "vcf_sample_name"))

# subset each species; just to know
cbp_all <- dat[which(dat$species == "Capsella bursa-pastoris"),]
cg <- dat[which(dat$species == "Capsella grandiflora"),]
cr <- dat[which(dat$species == "Capsella rubella"),]
co <- dat[which(dat$species == "Capsella orientalis"),]
np <- dat[which(dat$species == "Neslia paniculata"),]

### Not to be evaluated for odd heterozygosity
exp_het <- rbind(cg,np)

######### selecting only cbp I want--------
# remove F2s because I do not need those
cbp <- cbp_all[str_detect(cbp_all$sample_name, "F2_", negate = T),] #remove rows with F2 in the sample_name
# remove parents and pool
cbp <- cbp[str_detect(cbp$sample_name, "pool", negate = T),]
cbp <- cbp[str_detect(cbp$sample_name, "parent", negate = T),]

## get list of cbp I want to remove from vcf
rm <- cbp_all %>% anti_join(cbp)

# write removal list to file
write.table(rm$V1, 
            "~/Documents/PhD/Research/vcf_filtering/individuals/removeCBP_vcf.txt", 
            quote = F, sep = "\t", row.names = F, col.names = F)

# write C. grandiflora and Neslia paniculata to file so they are not removed during heterozygosity step
write.table(exp_het$V1, 
            "~/Documents/PhD/Research/vcf_filtering/individuals/CgNp.txt", 
            quote = F, sep = "\t", row.names = F, col.names = F)
