---
title: "Noodling on LD decay"
author: "Maya Wilson Brown"
date: "2024-10-16"
output: html_document
---


First, the script that generated the calculations of LD
based on population distinctions
```{r}
pops <- read.csv("~/Documents/PhD/Research/capsella_population_structure/cbp_pop_str.txt", sep = "\t", header=T)

nyc <- pops[which(str_detect(pops$vcf_sample_name, "L003")),]
easia <- pops[which(pops$k3population == "E_Asia"),]

write.table(nyc$vcf_sample_name, "~/Documents/PhD/Research/vcf_filtering/ld_decay/nyc_vcf_sample.txt",
            row.names = F,
            col.names = F,
            quote = F)

write.table(easia$vcf_sample_name, "~/Documents/PhD/Research/vcf_filtering/ld_decay/easia_vcf_sample.txt",
            row.names = F,
            col.names = F,
            quote = F)
```


```{bash, code = readLines("~/Documents/PhD/Research/vcf_filtering/ld_decay/noodling_LD_decay.sh"), eval = FALSE}
```

The actual calculation of linkage into averaged bins is done by the following python script.
```{bash, code = readLines("~/Documents/PhD/Research/vcf_filtering/ld_decay/ld_decay_calc.py"), eval = FALSE}
```

Then, to plot the output
```{r}
library(tidyverse)

# read in data
chr10_ld_bins <- read_tsv("~/Desktop/cbp_LD_JLv4_chr10.ld_decay_bins")

# plot LD decay
ggplot(chr10_ld_bins, aes(distance, avg_R2)) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) +
  geom_hline(yintercept = 0.04, color = "red")

# plot looks not how I expected.
# I guess 100-125kb windows are reasonable LD windows though?

# read in data
ld_bins <- read_tsv("~/Desktop/cbp_LD_JLv4_all.ld_decay_bins")


# plot LD decay
ggplot(ld_bins, aes(distance, avg_R2), colour = chr) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) +
  geom_hline(yintercept = 0.04, color = "red") +
  geom_vline(xintercept = 1) +
  facet_wrap(~chr) +
  theme_bw()

ggplot(subset(ld_bins, distance <= 150000), aes(distance, avg_R2), colour = chr) + geom_line() +
  xlab("Distance (bp)") + ylab(expression(italic(r)^2)) +
  geom_hline(yintercept = 0.04, color = "red") +
  geom_vline(xintercept = 1) +
  facet_wrap(~chr) +
  theme_bw()

```

